version: "3"
services:
  webserver:
    build: .
    ports:
      - "80:8099"
    depends_on:
      - redis
    #restart:
      #always


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --port 6379
    hostname: redis
    #restart:
     #always
