server:
  port:
    8091
spring:
  datasource:
    url: jdbc:h2:mem:eco-reading
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false # default true, ?? ??? false? ?? ?? ??

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          #       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
          use_sql_comments: true
          show_sql: true


