server:
  port:
    8099
spring:
  datasource:
    url: jdbc:h2:mem:eco-reading
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true



    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          #       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
          use_sql_comments: true
          show_sql: true


cloud:
  aws:
    s3:
      bucket: eco-reading-image-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIA2D2KRCMY4DWJKIU7
      secretKey: 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

