server:
  port:
    8099
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:eco-reading
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: josolha@gmail.com
    password: zrqhfrqlpnhyljmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

  redis:
    host: localhost
    port: 6379

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          #       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         format_sql: true
         use_sql_comments: true
         show_sql: true
cloud:
  aws:
    s3:
      bucket: eco-reading-image-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIA2D2KRCMY4DWJKIU7
      secretKey: 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

naver-property:
  clientId: 7mvqmOEqDyA7VG3qoDEa
  clientSecret: LHramuXw91